fos_user_change_password:
    pattern:  /{_locale}/change-password
    defaults: { _controller: "FOSUserBundle:ChangePassword:changePassword" }
    requirements: 
              _method:  GET|POST
              _locale: en|fr
       